"""first migration

Revision ID: b981cb66c56b
Revises: 
Create Date: 2022-02-01 14:27:11.807957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b981cb66c56b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('race', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=25), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('class_', sa.String(length=25), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('hair', sa.String(length=25), nullable=True),
    sa.Column('eyes', sa.String(length=25), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_age'), 'character', ['age'], unique=False)
    op.create_index(op.f('ix_character_class_'), 'character', ['class_'], unique=False)
    op.create_index(op.f('ix_character_eyes'), 'character', ['eyes'], unique=False)
    op.create_index(op.f('ix_character_gender'), 'character', ['gender'], unique=False)
    op.create_index(op.f('ix_character_hair'), 'character', ['hair'], unique=False)
    op.create_index(op.f('ix_character_level'), 'character', ['level'], unique=False)
    op.create_index(op.f('ix_character_name'), 'character', ['name'], unique=False)
    op.create_index(op.f('ix_character_notes'), 'character', ['notes'], unique=False)
    op.create_index(op.f('ix_character_race'), 'character', ['race'], unique=False)
    op.create_index(op.f('ix_character_saves'), 'character', ['saves'], unique=False)
    op.create_index(op.f('ix_character_weight'), 'character', ['weight'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_weight'), table_name='character')
    op.drop_index(op.f('ix_character_saves'), table_name='character')
    op.drop_index(op.f('ix_character_race'), table_name='character')
    op.drop_index(op.f('ix_character_notes'), table_name='character')
    op.drop_index(op.f('ix_character_name'), table_name='character')
    op.drop_index(op.f('ix_character_level'), table_name='character')
    op.drop_index(op.f('ix_character_hair'), table_name='character')
    op.drop_index(op.f('ix_character_gender'), table_name='character')
    op.drop_index(op.f('ix_character_eyes'), table_name='character')
    op.drop_index(op.f('ix_character_class_'), table_name='character')
    op.drop_index(op.f('ix_character_age'), table_name='character')
    op.drop_table('character')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
